# Generated by Django 4.0.4 on 2022-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simba_app', '0002_buffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monoffre',
            name='piece',
            field=models.IntegerField(null=True, verbose_name='Nombre de pièce'),
        ),
        migrations.AlterField(
            model_name='monoffre',
            name='tarif',
            field=models.IntegerField(null=True, verbose_name='Mon tarif'),
        ),
    ]
