# Generated by Django 4.0.4 on 2022-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simba_app', '0003_alter_monoffre_piece_alter_monoffre_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monoffre',
            name='piece',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de pièce'),
        ),
    ]
