# Generated by Django 4.0.4 on 2022-06-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simba_app', '0006_remove_commentaires_user_commentaires_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('pays', models.CharField(max_length=200)),
            ],
        ),
    ]
