# Generated by Django 4.0.4 on 2022-07-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simba_app', '0007_crud'),
    ]

    operations = [
        migrations.AddField(
            model_name='monoffre',
            name='users',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
