# Generated by Django 4.0.4 on 2022-07-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simba_app', '0009_alter_monoffre_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monoffre',
            name='users',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
